rails/majan/config/routes.rb
Rails.application.routes.draw do
  resources :majanlogs

  root 'majanlogs#index'

end

rails/majan/app/models/majanlog.rb
class Majanlog < ActiveRecord::Base
end

rails/majan/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

rails/majan/app/controllers/majanlogs_controller.rb
class MajanlogsController < ApplicationController
  before_action :set_majanlog, only: [:show, :edit, :update, :destroy]

  # GET /majanlogs
  # GET /majanlogs.json
  def index
    @majanlogs = Majanlog.all
  end

  # GET /majanlogs/1
  # GET /majanlogs/1.json
  def show
  end

  # GET /majanlogs/new
  def new
    @majanlog = Majanlog.new
  end

  # GET /majanlogs/1/edit
  def edit
  end

  # POST /majanlogs
  # POST /majanlogs.json
  def create
    @majanlog = Majanlog.new(majanlog_params)

    respond_to do |format|
      if @majanlog.save
        format.html { redirect_to @majanlog, notice: 'Majanlog was successfully created.' }
        format.json { render :show, status: :created, location: @majanlog }
      else
        format.html { render :new }
        format.json { render json: @majanlog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /majanlogs/1
  # PATCH/PUT /majanlogs/1.json
  def update
    respond_to do |format|
      if @majanlog.update(majanlog_params)
        format.html { redirect_to @majanlog, notice: 'Majanlog was successfully updated.' }
        format.json { render :show, status: :ok, location: @majanlog }
      else
        format.html { render :edit }
        format.json { render json: @majanlog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /majanlogs/1
  # DELETE /majanlogs/1.json
  def destroy
    @majanlog.destroy
    respond_to do |format|
      format.html { redirect_to majanlogs_url, notice: 'Majanlog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_majanlog
      @majanlog = Majanlog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def majanlog_params
      params.require(:majanlog).permit(:date, :num, :name1, :score1, :name2, :score2, :name3, :score3, :name4, :score4)
    end
end

rails/majan/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/majan/app/helpers/majanlogs_helper.rb
module MajanlogsHelper
end

rails/majan/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Majan</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

rails/majan/app/views/majanlogs/_form.html.erb
<%= form_for(@majanlog) do |f| %>
  <% if @majanlog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@majanlog.errors.count, "error") %> prohibited this majanlog from being saved:</h2>

      <ul>
      <% @majanlog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date, "日付" %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :num, "回数" %><br>
    <%= f.number_field :num %>
  </div>
  <div class="field">
    <%= f.label :name1, "メンバー1" %><br>
    <%= f.text_field :name1 %>
  </div>
  <div class="field">
    <%= f.label :score1, "点数1" %><br>
    <%= f.number_field :score1 %>
  </div>
  <div class="field">
    <%= f.label :name2, "メンバー2" %><br>
    <%= f.text_field :name2 %>
  </div>
  <div class="field">
    <%= f.label :score2, "点数2"  %><br>
    <%= f.number_field :score2 %>
  </div>
  <div class="field">
    <%= f.label :name3, "メンバー3" %><br>
    <%= f.text_field :name3 %>
  </div>
  <div class="field">
    <%= f.label :score3, "点数3" %><br>
    <%= f.number_field :score3 %>
  </div>
  <div class="field">
    <%= f.label :name4, "メンバー4" %><br>
    <%= f.text_field :name4 %>
  </div>
  <div class="field">
    <%= f.label :score4, "点数4" %><br>
    <%= f.number_field :score4 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails/majan/app/views/majanlogs/edit.html.erb
<h1>編集</h1>

<%= render 'form' %>

<%= link_to '詳細', @majanlog %> |
<%= link_to '戻る', majanlogs_path %>

rails/majan/app/views/majanlogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>麻雀の記録リスト</h1>

<table>
  <thead>
    <tr>
      <th>日付</th>
      <th>回数</th>
      <th>メンバー1</th>
      <th>点数1</th>
      <th>メンバー2</th>
      <th>点数2</th>
      <th>メンバー3</th>
      <th>点数3</th>
      <th>メンバー4</th>
      <th>点数4</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @majanlogs.each do |majanlog| %>
      <tr>
        <td><%= majanlog.date %></td>
        <td><%= majanlog.num %></td>
        <td><%= majanlog.name1 %></td>
        <td><%= majanlog.score1 %></td>
        <td><%= majanlog.name2 %></td>
        <td><%= majanlog.score2 %></td>
        <td><%= majanlog.name3 %></td>
        <td><%= majanlog.score3 %></td>
        <td><%= majanlog.name4 %></td>
        <td><%= majanlog.score4 %></td>
        <td><%= link_to '詳細', majanlog %></td>
        <td><%= link_to '編集', edit_majanlog_path(majanlog) %></td>
        <td><%= link_to '削除', majanlog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新規登録', new_majanlog_path %>

rails/majan/app/views/majanlogs/new.html.erb
<h1>新規登録</h1>

<%= render 'form' %>

<%= link_to '戻る', majanlogs_path %>

rails/majan/app/views/majanlogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>日付:</strong>
  <%= @majanlog.date %>
</p>

<p>
  <strong>回数:</strong>
  <%= @majanlog.num %>
</p>

<p>
  <strong>メンバー1:</strong>
  <%= @majanlog.name1 %>
</p>

<p>
  <strong>点数1:</strong>
  <%= @majanlog.score1 %>
</p>

<p>
  <strong>メンバー2:</strong>
  <%= @majanlog.name2 %>
</p>

<p>
  <strong>点数2:</strong>
  <%= @majanlog.score2 %>
</p>

<p>
  <strong>メンバー3:</strong>
  <%= @majanlog.name3 %>
</p>

<p>
  <strong>点数3:</strong>
  <%= @majanlog.score3 %>
</p>

<p>
  <strong>メンバー4:</strong>
  <%= @majanlog.name4 %>
</p>

<p>
  <strong>点数4:</strong>
  <%= @majanlog.score4 %>
</p>

<%= link_to '編集', edit_majanlog_path(@majanlog) %> |
<%= link_to '戻る', majanlogs_path %>